### ISSUE TITLE
Error with simulator when installing

### ISSUE THREAD

**Issue by SebastienValla** [massalabs/massa-sc-toolkit#38]
How to reproduce
in windows 
npx github:massalabs/massa-sc-toolkit init <projectName>
error : 
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node ./simulator/simulate.js --install

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sébastien\AppData\Local\npm-cache\_logs\2022-11-14T09_56_12_884Z-debug-0.log

    at checkExecSyncError (node:child_process:871:11)
    at execSync (node:child_process:943:15)
    at initialize (file:///C:/Users/S%C3%A9bastien/AppData/Local/npm-cache/_npx/5bbf080e09865dde/node_modules/@massalabs/sc-toolkit/initialize.js:26:5)
    at Object.handler (file:///C:/Users/S%C3%A9bastien/AppData/Local/npm-cache/_npx/5bbf080e09865dde/node_modules/@massalabs/sc-toolkit/cli.js:24:13)
    at file:///C:/Users/S%C3%A9bastien/AppData/Local/npm-cache/_npx/5bbf080e09865dde/node_modules/yargs/build/lib/command.js:204:54
    at maybeAsyncResult (file:///C:/Users/S%C3%A9bastien/AppData/Local/npm-cache/_npx/5bbf080e09865dde/node_modules/yargs/build/lib/utils/maybe-async-result.js:9:15)
    at CommandInstance.handleValidationAndGetResult (file:///C:/Users/S%C3%A9bastien/AppData/Local/npm-cache/_npx/5bbf080e09865dde/node_modules/yargs/build/lib/command.js:203:25)
    at CommandInstance.applyMiddlewareAndGetResult (file:///C:/Users/S%C3%A9bastien/AppData/Local/npm-cache/_npx/5bbf080e09865dde/node_modules/yargs/build/lib/command.js:243:20)
    at CommandInstance.runCommand (file:///C:/Users/S%C3%A9bastien/AppData/Local/npm-cache/_npx/5bbf080e09865dde/node_modules/yargs/build/lib/command.js:128:20) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(75) [Uint8Array] [
       10,  62,  32, 109, 121,  45, 10...]

**Comment by longgamma-massa** [comment]
@Thykof let's try reproducing this one as well... it might be the case it's solved with the new releases.

**Comment by Thykof** [comment]
Project initializer do not install the simulator anymore.
