### ISSUE TITLE
Deployer not working

### ISSUE THREAD

**Issue by noesusset** [massalabs/massa-sc-toolkit#88]
**Describe the bug**
The compiler doesnt compile the deployer file as it should be

**To Reproduce**

run :
`
npx @massalabs/sc-project-initializer@dev init testDir
npm install
npm install --save-dev @massalabs/massa-sc-compiler@dev
npm install @massalabs/massa-sc-deployer@dev
//create the .env file
npm run deploy
`
output:
`
> my-massa-sc@0.0.1 deploy
> npm run build && ts-node src/deploy.ts

> my-massa-sc@0.0.1 build
> npx massa-as-compile

2 files to compile

Error: ENOENT: no such file or directory, open '/home/noesusset/testDir4/node_modules/@massalabs/massa-sc-deployer/build/deployer.wasm'
    at Object.openSync (node:fs:600:3)
    at readFileSync (node:fs:468:35)
    at deploySC (file:///home/noesusset/testDir4/node_modules/@massalabs/massa-sc-deployer/src/index.ts:100:27)
    at async file:///home/noesusset/testDir4/src/deploy.ts:25:3 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/noesusset/testDir4/node_modules/@massalabs/massa-sc-deployer/build/deployer.wasm'
}
`

**Expected behavior**
It should build the deploy.ts file and create a deployer.wasm as it 
It should deploy the smart contract 

**Screenshots**

here in the old toolkit it was done 
![image](https://user-images.githubusercontent.com/96011618/211358095-08308b9f-b616-40be-b4f0-cbc85fbd6f7f.png)

**Versions**
The versions of software and packages the bug in present in (massa-as-sdk, toolkit, Thyra, web browser...)
`
@massalabs/massa-sc-compiler@0.0.3-dev.20230109142645
@massalabs/massa-sc-deployer@0.0.2-dev.20230106161458
@massalabs/sc-project-initializer@0.1.2-dev.20230106132854

`

**Additional context**

**Comment by Thykof** [comment]
Hi @noesusset , thank you for your feedback.

First, just to let you know that the command `npm run deploy` should:
- compile all assemblyscript file in /assembly/contracts
- execute typescript file /src/deploy.ts

Then, could you try again after doing `npm update @massalabs/massa-sc-compiler@dev` please? I have published a new nightly version that contains the `massa-sc-deployer/build/deployer.wasm`.

**Comment by noesusset** [comment]
Hello, yes indeed I saw after that what was really missing were the ```massa-sc-deployer/build``` directory and that the compiler now doesnt compile the deploy.ts file as before.
I just tried it and yes now it works perfectly fine thank you !
